import product1 from './images/products/product1.jpg'
import product2 from './images/products/product2.jpg'
import product3 from './images/products/product3.jpg'
import product4 from './images/products/product4.jpg'
import product5 from './images/products/product5.jpg'
import product6 from './images/products/product6.jpg'

export const restaurantProducts = [{
    id:1,
    title:'Creamy melt',
    price:150,
    inCart:false,
    count:0,
    total:0,
    color:'#50c9c3',
    type:'burger',
    image:product1
    },
    {
    id:2,
    title:'Super-beekon',
    price:300,
    inCart:false,
    count:0,
    total:0,
    color:'red',
    type:'burger',
    image:product2
    },
    {
    id:3,
    title:'Double patty',
    price:300,
    inCart:false,
    count:0,
    total:0,
    color:'#50c9c3',
    type:'burger',
    image:product3
    },
    {
    id:4,
    title:'Black bean',
    price:300,
    inCart:false,
    count:0,
    total:0,
    color:'#517fa4',
    type:'burger',
    image:product4
    },
    {
    id:5,
    title:'Bison Burger',
    price:150,
    inCart:false,
    count:0,
    total:0,
    color:'#00e3ae',
    type:'burger',
    image:product5
    },
    {
    id:6,
    title:'Banga',
    price:400,
    inCart:false,
    count:0,
    total:0,
    color:'red',
    type:'burger',
    image:product6
    
    },
    {
    id:7,
    title:'Fried-Rice',
    price:300,
    inCart:false,
    count:0,
    total:0,
    color:'#50c9c3',
    type:'burger',
    image:'./images/products/product1.jpg'
    },
    {
    id:8,
    title:'Amala',
    price:150,
    inCart:false,
    count:0,
    total:0,
    color:'#517fa4',
    type:'burger',
    image:'./images/products/product2.jpg'
    },
    {
    id:9,
    title:'Beans',
    price:250,
    inCart:false,
    count:0,
    total:0,
    color:'#50c9c3',
    type:'food',
    image:'./images/products/product3.jpg'
    },
    {
    id:10,
    title:'Okra',
    price:150,
    inCart:false,
    count:0,
    total:0,
    color:'red',
    type:'food',
    image:'./images/products/product4.jpg'
    },
    {
    id:11,
    title:'Coca-Cola',
    price:150,
    inCart:false,
    count:0,
    total:0,
    color:'#00e3ae',
    type:'food',
    image:'./images/products/product5.jpg'
    },
    {
    id:12,
    title:'Egusi',
    price:200,
    inCart:false,
    count:0,
    total:0,
    color:'red',
    type:'food',
    image:'./images/products/product6.jpg'
    },
    {
    id:13,
    title:'Eba',
    price:200,
    inCart:false,
    count:0,
    total:0,
    color:'#517fa4',
    type:'food',
    image:'./images/products/product1.jpg'
    },
    {
    id:14,
    title:'Oha',
    price:300,
    inCart:false,
    count:0,
    total:0,
    color:'red',
    type:'food',
    image:'./images/products/product2.jpg'
    },
    {
    id:15,
    title:'Dew',
    price:150,
    inCart:false,
    count:0,
    total:0,
    color:'#00E3AE',
    type:'food',
    image:'./images/products/product3.jpg'
    },
    {
    id:16,
    title:'Pounded Yam',
    price:200,
    inCart:false,
    count:0,
    total:0,
    color:'#517fa4',
    type:'food',
    image:'./images/products/product4.jpg'
    },
    {
    id:17,
    title:'Pasta',
    price:200,
    inCart:false,
    count:0,
    total:0,
    color:'#50c9c3',
    type:'food',
    image:'./images/products/product5.jpg'
    
    },
    {
    id:18,
    title:'Ofe',
    price:300,
    inCart:false,
    count:0,
    total:0,
    color:'red',
    type:'food',
    image:'./images/products/product6.jpg'
    },
    {
    id:19,
    title:'Jollof Rice',
    price:350,
    inCart:false,
    count:0,
    total:0,
    color:'#50c9c3',
    type:'food',
    image:'./images/products/product1.jpg'
    },
    {
    id:20,
    title:'Pepsi',
    price:150,
    inCart:false,
    count:0,
    total:0,
    color:'#00E3AE',
    type:'burger',
    image:'./images/products/product2.jpg'
    }
    ]
    //jollof, pasta white yam
    